server:
  port: 7010
  servlet:
    context-path: /api

spring:
  application:
    name: tm-bbs-rest
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: 124.221.124.200
    port: 6379
    password: 12345678

    # Millisecond
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
dubbo:
  application:
    name: tm-bbs-rest
  registry:
    address: zookeeper://124.221.124.200:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: 22001
  consumer:
    check: false
    timeout: 60000
  config-center:
    timeout: 60000
  provider:
    # With this you can throw a custom exception (otherwise it will always be a RuntimeException).
    filter: -exception


# customizing
interceptor:
  monitor:
    # Whether to enable monitoring
    status: true

cookie:
  # Cookies are written under the corresponding domain name
  domain: localhost.com

# Cross-domain configuration, sso login address
crossOrigin:
  address: http://sso.localhost.com

# open swagger
swagger:
  show: true

file:
  source:
    # Set the maximum value allowed for uploading source files (1024*1024*5=5M)
    length: 5242880