name: Check Java Version

on: [push, pull_request]

jobs:
  check-java-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'

    - name: Check Java Version in Committed Files
      run: |
        # Get the list of changed files in the commit
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

        for file in $changed_files; do
          # Check if the file contains "1.8" (Java 8)
          if grep -q "1.8" $file; then
            echo "File $file uses Java 1.8"
          else
            echo "File $file does not use Java 1.8"
            exit 1  # Exit with an error status to prevent the commit
          fi
        done
      
