name: Check Java Version

on: [push, pull_request]

jobs:
  check-java-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'

    - name: Check Java Version in Java Files
      run: |
        # Find all .java files in the repository
        java_files=$(find . -name "*.java")

        for file in $java_files; do
          # Try to compile each .java file
          javac $file 2>/dev/null

          # Check the exit code of javac
          if [ $? -eq 0 ]; then
            echo "File $file uses Java 8"
          else
            echo "File $file uses a different Java version"
            exit 1  # Exit with an error status to prevent the commit
          fi
        done
      
