name: Java 1.8 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
