name: Check Java Version

on: [push, pull_request]

jobs:
  check-java-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'

    - name: Check Java Version
      run: |
        # Get the Java version
        java -version

        # Check if the Java version contains "1.8" (Java 8)
        if [[ $(java -version 2>&1) == *"1.8"* ]]; then
          echo "Java version is 1.8 (Java 8)"
        else
          echo "Java version is not 1.8 (Java 8)"
          exit 1
        fi
