name: NginxCI
name: Node Version
on: [push, pull_request]
jobs:
  runs-on: ubuntu-latest
  services:
    nginx:
      image: nginx
      ports:
      - 8080:80
  steps:
   - uses: actions/checkout@v2
   - run:
       node -v
       curl localhost:8080
